### ISSUE TITLE
Can't get plugin/Homebridge to start

### ISSUE THREAD

**Issue by dustin141** [gadget-monk/homebridge-poolcontroller#9]
Hi, I have PoolController and PoolController DashPanel running successfully. I tried adding this plugin to my Homebridge and when its enabled it gets stuck in a loop constantly restarting Homebridge. Any ideas? Log below

[3/23/2022, 10:29:59 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 641C) is running on port 51391.
[3/23/2022, 10:29:59 AM] [PoolControllerPlatform] Pool controller reports it is ready, getting initial data
[3/23/2022, 10:29:59 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 2, id: poolController.2.Pool Light
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 3, id: poolController.3.AUX 2
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 4, id: poolController.4.AUX 3
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 5, id: poolController.5.AUX 4
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 6, id: poolController.6.Pool
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 11, id: poolController.11.High Speed
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 12, id: poolController.12.MID SPEED  
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 13, id: poolController.13.Feature 3
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 14, id: poolController.14.Feature 4
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 15, id: poolController.15.Feature 5
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 16, id: poolController.16.Feature 6
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 17, id: poolController.17.Feature 7
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 18, id: poolController.18.Feature 8
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached circuit accessory: circuitNumber: 20, id: poolController.20.AUX EXTRA
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached body accessory: Pool Heater
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Updating data for Pool body: state: true
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Using cached pump accessory: Intelliflo VS
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Updating pump to  true
[3/23/2022, 10:30:01 AM] [PoolControllerPlatform] Controller Delay and mode variables found, creating controller accessory: EasyTouch2 4P
[3/23/2022, 10:30:01 AM] ReferenceError: Format is not defined
    at new controllerMode (/usr/lib/node_modules/homebridge-poolcontroller/customTypes.js:86:21)
    at ContactSensor.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:336:56)
    at PoolControllerPlatform.addControllerAccessory (/usr/lib/node_modules/homebridge-poolcontroller/index.js:592:49)
    at PoolControllerPlatform.InitialData (/usr/lib/node_modules/homebridge-poolcontroller/index.js:296:22)
    at PoolControllerPlatform.validateVersion (/usr/lib/node_modules/homebridge-poolcontroller/index.js:156:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[3/23/2022, 10:30:01 AM] Got SIGTERM, shutting down Homebridge...
[3/23/2022, 10:30:06 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by gadget-monk** [comment]
the controller mode and delay reason custom characteristics were causing this error. I have disabled them for now. published an update.
